server: 
    # 端口
    port: 51005
    servlet: 
        # 配置访问路径添加项目名称
        context-path: /TimerTaskCollection
spring: 
  profiles:
    # 导入外部的配置文件， 文件名必须为application-xxx.yml格式 
    include: datasource, mybatis, email, redis, rabbitmq, rabbitmq-myconfig
# log4j日志配置
logging:
  config: classpath:application-log4j2.yml