mybatis: 
  # 配置mybatis扫描的mapp xml路径
  mapper-locations: classpath*:com/my/timertask/mapping/*.xml
  configuration:
      map-underscore-to-camel-case: true
  # 配置分页插件参数
  page-helper: 
    properties: 
      reasonable: true
      offsetAsPageNum: true
      rowBoundsWithCount: true
      dialect: mysql